services:
  postgres:
    image: postgres:17
    container_name: document-vault-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: document_vault
      # we can store this in secret but due to easy local setup we go with storing it in environment
      POSTGRES_PASSWORD: Vault#123  
      POSTGRES_DB: document_vault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: